# Users seed
# users = User.create([{ name: "John Doe", email: "johndoe@example.com", password: "Pattohoh001@" }, { name: "Sammy Luke", email: "sammylike@example.com", password: "Pattohoh001@" }])
# @user1 = User.create(name: "John Doe", email: "johndoe@example.com", password: "Pattohoh001@")
# Foods seed
# foods = Food.create([{ name: "Mangoes", measurement_unit: "Grams", price: 5, quantity: "100 g", author_id: 1 }, { name: "Apples", measurement_unit: "Kilograms", price: 1, quantity: "10 kg", author_id: 1 }, { name: "Chicken Breasts", measurement_unit: "Units", price: 3, quantity: "2 units", author_id: 1 }])

# Recipes seed
# recipes = Recip.create([{ name: "Classic Spaghetti Bolognese", preparation_time: "20 minutes", cooking_time: "One Hour", description: "Classic Spaghetti Bolognese is a popular Italian-inspired pasta dish that features a rich and flavorful meat sauce served over cooked spaghetti noodles. The sauce is made with ground meat (such as beef, pork, or a combination), onions, garlic, carrots, and celery, cooked in a tomato-based sauce with herbs and spices. The dish is typically finished with a generous sprinkle of grated Parmesan cheese and fresh herbs for added aroma and flavor. To make Classic Spaghetti Bolognese, the prep begins with chopping the vegetables and measuring the ingredients. Then, the meat is cooked in a pan until browned, followed by sautéing the vegetables until softened. Tomato sauce, crushed tomatoes, herbs (such as oregano, thyme, and bay leaves), and a pinch of sugar to balance the acidity of the tomatoes are added to the pan. The sauce is simmered over low heat for a period of time, allowing the flavors to meld together and develop.", public: true, author_id: 1 }, { name: "Classic Spaghetti Bolognese", preparation_time: "20 minutes", cooking_time: "One Hour", description: "Classic Spaghetti Bolognese is a popular Italian-inspired pasta dish that features a rich and flavorful meat sauce served over cooked spaghetti noodles. The sauce is made with ground meat (such as beef, pork, or a combination), onions, garlic, carrots, and celery, cooked in a tomato-based sauce with herbs and spices. The dish is typically finished with a generous sprinkle of grated Parmesan cheese and fresh herbs for added aroma and flavor. To make Classic Spaghetti Bolognese, the prep begins with chopping the vegetables and measuring the ingredients. Then, the meat is cooked in a pan until browned, followed by sautéing the vegetables until softened. Tomato sauce, crushed tomatoes, herbs (such as oregano, thyme, and bay leaves), and a pinch of sugar to balance the acidity of the tomatoes are added to the pan. The sauce is simmered over low heat for a period of time, allowing the flavors to meld together and develop.", author_id: 1 }])

#Recipe_Foods seed
# recipe_foods = RecipeFood.create([{ quantity: "20 g", recip_id: 1, food_id: 15 }, { quantity: "2 kg", recip_id: 1, food_id: 16 }])
